version: '3' 

services:
  asterisk:
    build: .
    image: alpine-asterisk
    restart: always
    container_name: alpine-asterisk
    command: > 
      sh -c 'cd /opt/scripts &&
            python3 /opt/scripts/create-sample-config.py &&
            python3 /opt/scripts/create-users.py &&
            asterisk -f'
#    ports:
    network_mode: host
#      - "5060:5060/udp"                     # SIP UDP port
#      - "5060:5060"                         # SIP TCP port
#      - "5061:5061"                         # SIP TLS port
#      - "10000-10099:10000-10099/udp"       # RTP ports
    volumes:
      - "/etc/asterisk:/etc/asterisk:rw"
      - "./scripts:/opt/scripts:r"